load_encoder:
#  ckpt_fname: 'none'
  ckpt_fname: 'checkpoints/encoder-ep_300-6_v2.ckpt'
  backbone_type: 'ResNet34Encoder'

exp_params:
  LR:
    encoder: 0.0005
    clf: 0.001
  out_size_enc: 512
  freeze_encoders: True  # if `True` -> Linear Evaluation
  freeze_bn_stat_train: False  # True if `train_data_ratio` is small else False
  weight_decay: 0.
  label_smoothing: 0.
  gradient_clip_val: 0.5
  n_classes: 8
  use_class_weight: True

trainer_params:
  gpus:
    - 0
  max_epochs: 100

dataset:
  train_data_ratio: 0.8
  test_data_ratio: 0.2
  train_test_split_rand_seed: 0
  batch_size: 64
  num_workers: 20 #0
  return_single_spectrogram_train: True
  return_single_spectrogram_test: False
  is_ssl: False

augmentations:
  - 'ToTensor'