model_params:
  name: 'VIbCRegTNC'
  in_channels: 1
  out_size_enc: 512
  proj_hid: 4096
  proj_out: 4096
  backbone_type: 'ResNet34Encoder'

exp_params:
  lambda_: 10 # sim loss
  mu: 10  # var loss
  nu: 10  # cov loss
  rho: 25.  # TNC loss
  LR: 0.001
  weight_decay: 0. #0.00001
  model_save_ep_period: 50
  knn_acc_record_ep_period: 1
  gradient_clip_val: 0.5

trainer_params:
  gpus:
    - 1
  max_epochs: 300

dataset:
  train_data_ratio: 0.8
  test_data_ratio: 0.2
  train_test_split_rand_seed: 0
  batch_size: 128
  num_workers: 20 # 8
  return_single_spectrogram_train: True
  return_single_spectrogram_test: True
  is_ssl: True

augmentations:
  - 'NeighboringCrop'
  #  - 'RandomCrop'
  - 'ToTensor'
