dataset:
  train_data_ratio: 0.8
  test_data_ratio: 0.2
  train_test_split_rand_seed: 0
  batch_size: 64
  num_workers: 0  # recommend to set to your #cpus

backbone_with_clf_type: 'ResNet18'  # AlexNet; ResNet18; ResNet34

exp_params:
  LR: 0.001
  weight_decay: 0.0001
  use_class_weight: True
  model_save_ep_period: 50  # -1 denotes no-save

trainer_params:
  gpus:
    - 0
  max_epochs: 50