dataset:
  train_data_ratio: 0.8
  test_data_ratio: 0.2
  train_test_split_rand_seed: 0
  batch_size: 32
  num_workers: 0

backbone_with_clf_type: 'ResNet34'

exp_params:
  LR: 0.001
  weight_decay: 0.00001
  use_class_weight: False

trainer_params:
  gpus:
    - 0
  max_epochs: 100